// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raqwrslwuefyikijlbma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcXdyc2x3dWVmeWlraWpsYm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjcyMTgsImV4cCI6MjA3MDQwMzIxOH0.HSyeMVY5hhY7xtMOUcF9dLNWkifgzXfrXwRemtm7YWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});